"""initial schema

Revision ID: 35bee8be9862
Revises: 
Create Date: 2026-08-31 19:07:43.977167
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401 - used by dialect variants
from sqlalchemy.dialects import postgresql  # noqa: F401 - used by dialect variants

# Custom column types referenced by autogenerated definitions.
import app.db.types  # noqa: F401
from alembic import op

revision: str = '35bee8be9862'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repair_teams',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('zone', sa.String(length=120), nullable=True),
    sa.Column('base_latitude', sa.Float(), nullable=True),
    sa.Column('base_longitude', sa.Float(), nullable=True),
    sa.Column('specialities', sa.String(length=200), nullable=True),
    sa.Column('max_concurrent_jobs', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('repair_teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repair_teams_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_repair_teams_zone'), ['zone'], unique=False)

    op.create_table('seeded_places',
    sa.Column('place_type', sa.Enum('HOSPITAL', 'SCHOOL', 'BUS_STOP', 'MAJOR_INTERSECTION', 'EMERGENCY_SERVICE', name='placetype', native_enum=False, length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seeded_places', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seeded_places_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_seeded_places_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_seeded_places_lat_lon', ['latitude', 'longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_seeded_places_place_type'), ['place_type'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('CITIZEN', 'ADMIN', 'REPAIR_TEAM', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('team_id', app.db.types.GUID(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['repair_teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_team_id'), ['team_id'], unique=False)

    op.create_table('complaints',
    sa.Column('complaint_number', sa.String(length=24), nullable=False),
    sa.Column('reporter_id', app.db.types.GUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reported_damage_type', sa.Enum('POTHOLE', 'CRACKED_ROAD', 'FLOODING', 'DAMAGED_SIDEWALK', 'BROKEN_STREETLIGHT', 'OTHER', 'UNKNOWN', name='damagetype', native_enum=False, length=30), nullable=True),
    sa.Column('damage_type', sa.Enum('POTHOLE', 'CRACKED_ROAD', 'FLOODING', 'DAMAGED_SIDEWALK', 'BROKEN_STREETLIGHT', 'OTHER', 'UNKNOWN', name='damagetype', native_enum=False, length=30), nullable=False),
    sa.Column('road_name', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AI_ANALYZED', 'PRIORITIZED', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', 'DUPLICATE', name='complaintstatus', native_enum=False, length=20), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('priority_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='prioritylevel', native_enum=False, length=20), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=False),
    sa.Column('manual_priority_override', sa.Float(), nullable=True),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_of_id', app.db.types.GUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['complaints.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaints_complaint_number'), ['complaint_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_complaints_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_damage_type'), ['damage_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_duplicate_of_id'), ['duplicate_of_id'], unique=False)
        batch_op.create_index('ix_complaints_lat_lon', ['latitude', 'longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_priority_level'), ['priority_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_priority_score'), ['priority_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_status'), ['status'], unique=False)
        batch_op.create_index('ix_complaints_status_priority', ['status', 'priority_score'], unique=False)
        batch_op.create_index('ix_complaints_type_created', ['damage_type', 'created_at'], unique=False)

    op.create_table('audit_logs',
    sa.Column('actor_id', app.db.types.GUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', app.db.types.GUID(), nullable=True),
    sa.Column('complaint_id', app.db.types.GUID(), nullable=True),
    sa.Column('old_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('new_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)

    op.create_table('complaint_images',
    sa.Column('complaint_id', app.db.types.GUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=700), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('REPORT', 'REPAIR_EVIDENCE', name='imagekind', native_enum=False, length=30), nullable=False),
    sa.Column('perceptual_hash', sa.String(length=64), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaint_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_images_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_images_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_images_perceptual_hash'), ['perceptual_hash'], unique=False)

    op.create_table('complaint_status_history',
    sa.Column('complaint_id', app.db.types.GUID(), nullable=False),
    sa.Column('from_status', sa.Enum('PENDING', 'AI_ANALYZED', 'PRIORITIZED', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', 'DUPLICATE', name='complaintstatus', native_enum=False, length=20), nullable=True),
    sa.Column('to_status', sa.Enum('PENDING', 'AI_ANALYZED', 'PRIORITIZED', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', 'DUPLICATE', name='complaintstatus', native_enum=False, length=20), nullable=False),
    sa.Column('changed_by_id', app.db.types.GUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaint_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_status_history_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_status_history_created_at'), ['created_at'], unique=False)

    op.create_table('locations',
    sa.Column('complaint_id', app.db.types.GUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy_meters', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('road_name', sa.String(length=200), nullable=True),
    sa.Column('ward', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('road_importance', sa.Float(), nullable=False),
    sa.Column('geocode_source', sa.String(length=50), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('complaint_id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_created_at'), ['created_at'], unique=False)

    op.create_table('nearby_places',
    sa.Column('complaint_id', app.db.types.GUID(), nullable=False),
    sa.Column('place_type', sa.Enum('HOSPITAL', 'SCHOOL', 'BUS_STOP', 'MAJOR_INTERSECTION', 'EMERGENCY_SERVICE', name='placetype', native_enum=False, length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('distance_meters', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nearby_places', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nearby_places_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nearby_places_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_nearby_places_place_type'), ['place_type'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('event', sa.String(length=60), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', 'SMS', 'PUSH', name='notificationchannel', native_enum=False, length=20), nullable=False),
    sa.Column('complaint_id', app.db.types.GUID(), nullable=True),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('potential_duplicates',
    sa.Column('complaint_id', app.db.types.GUID(), nullable=False),
    sa.Column('duplicate_complaint_id', app.db.types.GUID(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('distance_meters', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SUGGESTED', 'CONFIRMED', 'REJECTED', name='duplicatestatus', native_enum=False, length=20), nullable=False),
    sa.Column('reviewed_by_id', app.db.types.GUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['duplicate_complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('complaint_id', 'duplicate_complaint_id', name='uq_duplicate_pair')
    )
    with op.batch_alter_table('potential_duplicates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_potential_duplicates_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_potential_duplicates_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_potential_duplicates_duplicate_complaint_id'), ['duplicate_complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_potential_duplicates_status'), ['status'], unique=False)

    op.create_table('priority_assessments',
    sa.Column('complaint_id', app.db.types.GUID(), nullable=False),
    sa.Column('severity_factor', sa.Float(), nullable=False),
    sa.Column('traffic_factor', sa.Float(), nullable=False),
    sa.Column('location_factor', sa.Float(), nullable=False),
    sa.Column('history_factor', sa.Float(), nullable=False),
    sa.Column('severity_points', sa.Float(), nullable=False),
    sa.Column('traffic_points', sa.Float(), nullable=False),
    sa.Column('location_points', sa.Float(), nullable=False),
    sa.Column('history_points', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='prioritylevel', native_enum=False, length=20), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('weights', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('signals', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('weather_multiplier', sa.Float(), nullable=False),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('priority_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_priority_assessments_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_priority_assessments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_priority_assessments_total_score'), ['total_score'], unique=False)

    op.create_table('repair_assignments',
    sa.Column('complaint_id', app.db.types.GUID(), nullable=False),
    sa.Column('team_id', app.db.types.GUID(), nullable=False),
    sa.Column('assigned_by_id', app.db.types.GUID(), nullable=True),
    sa.Column('status', sa.Enum('ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'VERIFIED', 'CANCELLED', name='assignmentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_id', app.db.types.GUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['repair_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repair_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repair_assignments_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repair_assignments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_repair_assignments_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_repair_assignments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_repair_assignments_team_id'), ['team_id'], unique=False)

    op.create_table('traffic_snapshots',
    sa.Column('complaint_id', app.db.types.GUID(), nullable=False),
    sa.Column('level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', name='trafficlevel', native_enum=False, length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('estimated_vehicles_per_hour', sa.Integer(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traffic_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traffic_snapshots_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_traffic_snapshots_created_at'), ['created_at'], unique=False)

    op.create_table('weather_snapshots',
    sa.Column('complaint_id', app.db.types.GUID(), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('rainfall_mm_24h', sa.Float(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('risk_multiplier', sa.Float(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_snapshots_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weather_snapshots_created_at'), ['created_at'], unique=False)

    op.create_table('ai_analyses',
    sa.Column('complaint_id', app.db.types.GUID(), nullable=False),
    sa.Column('image_id', app.db.types.GUID(), nullable=True),
    sa.Column('damage_type', sa.Enum('POTHOLE', 'CRACKED_ROAD', 'FLOODING', 'DAMAGED_SIDEWALK', 'BROKEN_STREETLIGHT', 'OTHER', 'UNKNOWN', name='damagetype', native_enum=False, length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=False),
    sa.Column('damaged_area_ratio', sa.Float(), nullable=False),
    sa.Column('detection_count', sa.Integer(), nullable=False),
    sa.Column('is_confident', sa.Boolean(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('severity_explanation', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['complaint_images.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analyses_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analyses_created_at'), ['created_at'], unique=False)

    op.create_table('repair_evidence',
    sa.Column('assignment_id', app.db.types.GUID(), nullable=False),
    sa.Column('submitted_by_id', app.db.types.GUID(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=700), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['repair_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repair_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repair_evidence_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repair_evidence_created_at'), ['created_at'], unique=False)

    op.create_table('ai_detections',
    sa.Column('analysis_id', app.db.types.GUID(), nullable=False),
    sa.Column('damage_type', sa.Enum('POTHOLE', 'CRACKED_ROAD', 'FLOODING', 'DAMAGED_SIDEWALK', 'BROKEN_STREETLIGHT', 'OTHER', 'UNKNOWN', name='damagetype', native_enum=False, length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox_x', sa.Float(), nullable=False),
    sa.Column('bbox_y', sa.Float(), nullable=False),
    sa.Column('bbox_width', sa.Float(), nullable=False),
    sa.Column('bbox_height', sa.Float(), nullable=False),
    sa.Column('area_ratio', sa.Float(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_detections_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_detections_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_detections_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_detections_analysis_id'))

    op.drop_table('ai_detections')
    with op.batch_alter_table('repair_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repair_evidence_created_at'))
        batch_op.drop_index(batch_op.f('ix_repair_evidence_assignment_id'))

    op.drop_table('repair_evidence')
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_analyses_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_analyses_complaint_id'))

    op.drop_table('ai_analyses')
    with op.batch_alter_table('weather_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_snapshots_created_at'))
        batch_op.drop_index(batch_op.f('ix_weather_snapshots_complaint_id'))

    op.drop_table('weather_snapshots')
    with op.batch_alter_table('traffic_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traffic_snapshots_created_at'))
        batch_op.drop_index(batch_op.f('ix_traffic_snapshots_complaint_id'))

    op.drop_table('traffic_snapshots')
    with op.batch_alter_table('repair_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repair_assignments_team_id'))
        batch_op.drop_index(batch_op.f('ix_repair_assignments_status'))
        batch_op.drop_index(batch_op.f('ix_repair_assignments_due_at'))
        batch_op.drop_index(batch_op.f('ix_repair_assignments_created_at'))
        batch_op.drop_index(batch_op.f('ix_repair_assignments_complaint_id'))

    op.drop_table('repair_assignments')
    with op.batch_alter_table('priority_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_priority_assessments_total_score'))
        batch_op.drop_index(batch_op.f('ix_priority_assessments_created_at'))
        batch_op.drop_index(batch_op.f('ix_priority_assessments_complaint_id'))

    op.drop_table('priority_assessments')
    with op.batch_alter_table('potential_duplicates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_potential_duplicates_status'))
        batch_op.drop_index(batch_op.f('ix_potential_duplicates_duplicate_complaint_id'))
        batch_op.drop_index(batch_op.f('ix_potential_duplicates_created_at'))
        batch_op.drop_index(batch_op.f('ix_potential_duplicates_complaint_id'))

    op.drop_table('potential_duplicates')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_event'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_complaint_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('nearby_places', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nearby_places_place_type'))
        batch_op.drop_index(batch_op.f('ix_nearby_places_created_at'))
        batch_op.drop_index(batch_op.f('ix_nearby_places_complaint_id'))

    op.drop_table('nearby_places')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_created_at'))
        batch_op.drop_index(batch_op.f('ix_locations_city'))

    op.drop_table('locations')
    with op.batch_alter_table('complaint_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_status_history_created_at'))
        batch_op.drop_index(batch_op.f('ix_complaint_status_history_complaint_id'))

    op.drop_table('complaint_status_history')
    with op.batch_alter_table('complaint_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_images_perceptual_hash'))
        batch_op.drop_index(batch_op.f('ix_complaint_images_created_at'))
        batch_op.drop_index(batch_op.f('ix_complaint_images_complaint_id'))

    op.drop_table('complaint_images')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_complaint_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index('ix_complaints_type_created')
        batch_op.drop_index('ix_complaints_status_priority')
        batch_op.drop_index(batch_op.f('ix_complaints_status'))
        batch_op.drop_index(batch_op.f('ix_complaints_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_complaints_priority_score'))
        batch_op.drop_index(batch_op.f('ix_complaints_priority_level'))
        batch_op.drop_index('ix_complaints_lat_lon')
        batch_op.drop_index(batch_op.f('ix_complaints_duplicate_of_id'))
        batch_op.drop_index(batch_op.f('ix_complaints_damage_type'))
        batch_op.drop_index(batch_op.f('ix_complaints_created_at'))
        batch_op.drop_index(batch_op.f('ix_complaints_complaint_number'))

    op.drop_table('complaints')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_team_id'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('seeded_places', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seeded_places_place_type'))
        batch_op.drop_index('ix_seeded_places_lat_lon')
        batch_op.drop_index(batch_op.f('ix_seeded_places_created_at'))
        batch_op.drop_index(batch_op.f('ix_seeded_places_city'))

    op.drop_table('seeded_places')
    with op.batch_alter_table('repair_teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repair_teams_zone'))
        batch_op.drop_index(batch_op.f('ix_repair_teams_created_at'))

    op.drop_table('repair_teams')
    # ### end Alembic commands ###
